# Generated by Django 4.2.21 on 2025-05-27 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datos_celular',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado_celular',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='user',
            name='motivo_ingreso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_celular',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado responsable'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_ingreso', models.CharField(blank=True, max_length=45, null=True, verbose_name='Motivo de ingreso')),
                ('tipo_celular', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de celular')),
                ('datos_celular', models.CharField(blank=True, max_length=45, null=True, verbose_name='Datos del celular')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado_celular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.estado', verbose_name='Estado del celular')),
                ('user', models.OneToOneField(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='administracion.cliente', verbose_name='Cliente'),
        ),
    ]
