# Generated by Django 4.2.21 on 2025-05-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_user_datos_celular_remove_user_estado_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de pago')),
            ],
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='total_Apagar',
            new_name='total_a_pagar',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='id_ventas',
            new_name='venta',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='datos_celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='motivo_ingreso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_celular',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(default=1, max_length=45, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=1, verbose_name='Número de Teléfono'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_ingreso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de ingreso')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('marca_celular', models.CharField(blank=True, max_length=45, null=True, verbose_name='Marca del celular')),
                ('referencia_celular', models.CharField(blank=True, max_length=45, null=True, verbose_name='Referencia del celular')),
                ('precio_total', models.IntegerField(blank=True, null=True, verbose_name='Precio total')),
                ('abono', models.IntegerField(blank=True, null=True, verbose_name='Abono')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='administracion.cliente')),
                ('estado_reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.estado', verbose_name='Estado de la Reparación')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.tipopago', verbose_name='Tipo de pago')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.tipopago', verbose_name='Tipo de pago'),
        ),
    ]
