# Generated by Django 4.2.21 on 2025-05-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_tipopago_rename_id_producto_detalleventa_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='estado_venta',
        ),
        migrations.AddField(
            model_name='ventas',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.tipopago', verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de la venta'),
        ),
    ]
