# Generated by Django 4.2.22 on 2025-06-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_detalleventa_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='Número de Teléfono'),
        ),
    ]
